@startuml
!include ../../c4/C4_Container.puml

LAYOUT_LEFT_RIGHT()

title Диаграмма Контекста системы мониторинга температуры

Person(user, "Пользователь", "Мониторит температуру","11111","11111","22222","")
System_Ext(sensor, "Датчики температуры", "Предоставляет данные о температуре")
'Boundary($alias, $label, "", $allTags, $link, $descr)

System_Boundary(monolith, "Монолитное приложение") {
    Container(client, "", "Мониторит температуру и взаимодействует с пользователем")
    Container(client, "", "Мониторит температуру и взаимодействует с пользователем")
}

Rel(user, monolith, "Просмотр данных о температуре")
Rel(monolith, sensor, "Получение данных о температуре")

'SHOW_LEGEND()

@enduml